require "seats.keyboard.groups.awesome"
require "seats.keyboard.groups.bling"
require "seats.keyboard.groups.client"
require "seats.keyboard.groups.focus"
require "seats.keyboard.groups.layout"
require "seats.keyboard.groups.tags"
